ARG IMAGE_TAG=10.0-noble

FROM mcr.microsoft.com/dotnet/aspnet:$IMAGE_TAG AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:$IMAGE_TAG AS build
WORKDIR /

# Copia os arquivos de projeto primeiro para restaurar as dependências e aproveitar o cache do Docker
COPY ["src/PopDesing.Api/PopDesing.Api.csproj", "src/PopDesing.Api/"]
COPY ["src/PopDesing.Application/PopDesing.Application.csproj", "src/PopDesing.Application/"]
COPY ["src/PopDesing.Domain/PopDesing.Domain.csproj", "src/PopDesing.Domain/"]
COPY ["src/PopDesing.Infrastructure/PopDesing.Infrastructure.csproj", "src/PopDesing.Infrastructure/"]

RUN dotnet restore "src/PopDesing.Api/PopDesing.Api.csproj"

# Copia o restante do código fonte
COPY . .
WORKDIR "/src/PopDesing.Api"
RUN dotnet build "./PopDesing.Api.csproj" -c Release -o /app/build

# Esta fase é usada para publicar o projeto de serviço a ser copiado para a fase final
FROM build AS publish
RUN dotnet publish "PopDesing.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS runtime
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PopDesing.Api.dll"]
