ARG IMAGE_TAG=10.0-noble

FROM mcr.microsoft.com/dotnet/aspnet:$IMAGE_TAG AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:$IMAGE_TAG AS build
WORKDIR /

# Copia os arquivos de projeto primeiro para restaurar as dependências e aproveitar o cache do Docker
COPY ["src/PopDesign.Api/PopDesign.Api.csproj", "src/PopDesign.Api/"]
COPY ["src/PopDesign.Application/PopDesign.Application.csproj", "src/PopDesign.Application/"]
COPY ["src/PopDesign.Domain/PopDesign.Domain.csproj", "src/PopDesign.Domain/"]
COPY ["src/PopDesign.Infrastructure/PopDesign.Infrastructure.csproj", "src/PopDesign.Infrastructure/"]

RUN dotnet restore "src/PopDesign.Api/PopDesign.Api.csproj"

# Copia o restante do código fonte
COPY . .
WORKDIR "/src/PopDesign.Api"
RUN dotnet build "./PopDesign.Api.csproj" -c Release -o /app/build

# Esta fase é usada para publicar o projeto de serviço a ser copiado para a fase final
FROM build AS publish
RUN dotnet publish "PopDesign.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS runtime
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PopDesign.Api.dll"]
